version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123@
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: